use crate::{Entity, SimulationConfig, SimulationResult};
use crate::physics::PhysicsEngine;
use rand::{Rng, SeedableRng};
use rand::rngs::StdRng;
use rayon::prelude::*;
use std::time::Instant;

pub struct SimulationEngine {
    config: SimulationConfig,
        entities: Vec<Entity>,
            physics: PhysicsEngine,
                current_step: usize,
                    }

                    impl SimulationEngine {
                        pub fn new(config: SimulationConfig) -> Self {
                                let mut rng = StdRng::seed_from_u64(config.seed);
                                        let entities = Self::initialize_entities(config.entity_count, &mut rng);
                                                
                                                        Self {
                                                                    config,
                                                                                entities,
                                                                                            physics: PhysicsEngine::new(),
                                                                                                        current_step: 0,
                                                                                                                            }
                                                                                                                                }
                                                                                                                                    
                                                                                                                                        fn initialize_entities(count: usize, rng: &mut StdRng) -> Vec<Entity> {
                                                                                                                                                let seeds: Vec<u64> = (0..count).map(|_| rng.gen()).collect();
                                                                                                                                                seeds
                                                                                                                                                            .into_par_iter()
                                                                                                                                                            .enumerate()
                                                                                                                                                                        .map_init(
                                                                                                                                                                                        || StdRng::from_seed([0u8; 32]), // Dummy-Initialisierung, wird durch den Seed überschrieben
                                                                                                                                                                                                        |local_rng, (id, seed_val)| {
                                                                                                                                                                                                            *local_rng = StdRng::seed_from_u64(seed_val);
                                                                                                                                                                                                                            let mut entity = Entity::new(id);
                                                                                                                                                                                                                                                entity.state.position.x = local_rng.gen_range(-10.0..10.0);
                                                                                                                                                                                                                                                                    entity.state.position.y = local_rng.gen_range(-10.0..10.0);
                                                                                                                                                                                                                                                                                        entity.state.position.z = local_rng.gen_range(-10.0..10.0);
                                                                                                                                                                                                                                                                                                            entity.state.velocity.x = local_rng.gen_range(-1.0..1.0);
                                                                                                                                                                                                                                                                                                                                entity.state.velocity.y = local_rng.gen_range(-1.0..1.0);
                                                                                                                                                                                                                                                                                                                                                    entity.state.velocity.z = local_rng.gen_range(-1.0..1.0);
                                                                                                                                                                                                                                                                                                                                                                        entity.state.mass = local_rng.gen_range(0.5..2.0);
                                                                                                                                                                                                                                                                                                                                                                                            entity
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                    .collect()
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                pub fn run(&mut self) -> SimulationResult {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        let start_time = Instant::now();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                let mut step_times = Vec::new();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                println!("Starting simulation...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for step in 0..self.config.max_steps {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let step_start = Instant::now();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.step();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    let step_duration = step_start.elapsed();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                step_times.push(step_duration.as_secs_f64());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if step % (self.config.max_steps / 10) == 0 {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let active_entities = self.entities.iter().filter(|e| e.active).count();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        println!("Step {}/{}, Active entities: {}", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 step + 1, self.config.max_steps, active_entities);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     let total_duration = start_time.elapsed();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     SimulationResult {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 total_steps: self.config.max_steps,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             total_duration: total_duration.as_secs_f64(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         final_entities: self.entities.clone(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     step_times,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 active_entities: self.entities.iter().filter(|e| e.active).count(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     fn step(&mut self) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             let forces = self.physics.calculate_forces(&self.entities);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             self.entities
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         .par_iter_mut()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     .zip(forces.par_iter())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .for_each(|(entity, force)| {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 entity.update(self.config.time_step, *force);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             self.physics.apply_boundary_conditions(&mut self.entities, 50.0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     self.current_step += 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 pub fn get_active_entity_count(&self) -> usize {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         self.entities.iter().filter(|e| e.active).count()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }