use crate::entity::{Entity, Vector3};
use rayon::prelude::*;

pub struct PhysicsEngine {
    gravity: Vector3,
        damping: f64,
        }

        impl PhysicsEngine {
            pub fn new() -> Self {
                    Self {
                                gravity: Vector3::new(0.0, -9.81, 0.0),
                                            damping: 0.99,
                                                    }
                                                        }
                                                            
                                                                pub fn calculate_forces(&self, entities: &[Entity]) -> Vec<Vector3> {
                                                                        entities
                                                                                    .par_iter()
                                                                                                .map(|entity| {
                                                                                                                if !entity.active {
                                                                                                                                    return Vector3::zero();
                                                                                                                                                    }
                                                                                                                                                                    
                                                                                                                                                                                    let gravitational_force = self.gravity * entity.state.mass;
                                                                                                                                                                                                    let damping_force = entity.state.velocity * (-self.damping);
                                                                                                                                                                                                                    
                                                                                                                                                                                                                                    gravitational_force + damping_force
                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                            .collect()
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                        pub fn apply_boundary_conditions(&self, entities: &mut [Entity], bounds: f64) {
                                                                                                                                                                                                                                                                                entities.par_iter_mut().for_each(|entity| {
                                                                                                                                                                                                                                                                                            if !entity.active {
                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                let pos = &mut entity.state.position;
                                                                                                                                                                                                                                                                                                                                                            let vel = &mut entity.state.velocity;
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                    if pos.x.abs() > bounds {
                                                                                                                                                                                                                                                                                                                                                                                                    pos.x = pos.x.signum() * bounds;
                                                                                                                                                                                                                                                                                                                                                                                                                    vel.x = -vel.x * 0.8;
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                            if pos.y.abs() > bounds {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            pos.y = pos.y.signum() * bounds;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            vel.y = -vel.y * 0.8;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if pos.z.abs() > bounds {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pos.z = pos.z.signum() * bounds;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    vel.z = -vel.z * 0.8;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            impl Default for PhysicsEngine {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fn default() -> Self {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Self::new()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }